<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SonarQubeTestProject>true</SonarQubeTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SharedKernel\GarageFlow.SharedKernel.csproj" />
    <ProjectReference Include="..\..\Domain\GarageFlow.Domain.csproj" />
  </ItemGroup>

</Project>
