apiVersion: v1
kind: Service
metadata:
  name: garageflow-api
  namespace: garageflow
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
      nodePort: 30080
      protocol: TCP
